services:
  - type: web
    name: django-project2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn djangoapi3.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: djangoapi3.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: django-project2-db
          property: connectionString 