# Generated by Django 5.2 on 2025-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0002_remove_leave_approved_by_remove_leave_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
