# Generated by Django 5.2 on 2025-05-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="position",
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
